In [1]:
### 1. 넘파이 (Numpy) ###

# - 선형대수
# - 대량 데이터의 빠른 배열 연산
# - C / C++ 저수준 언어 기반의 호환 API 제공
# - 라이브러리 사용 : import numpy as np
# - np.array() : 파이썬 리스트 등을 ndarray 로 변환

In [2]:
import numpy as np

In [3]:
# ndarray 생성

array1 = np.array([1, 2, 3])
print(type(array1))
print(array1.shape)

<class 'numpy.ndarray'>
(3,)


In [4]:
array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print(type(array2))
print(array2.shape)

<class 'numpy.ndarray'>
(2, 3)


In [5]:
array3 = np.array([[1, 2, 3]])
print(type(array3))
print(array3.shape)

<class 'numpy.ndarray'>
(1, 3)


In [6]:
# 차원

print(array1.ndim, array2.ndim, array3.ndim)

1 2 2


In [7]:
# 데이터 타입 ndarray
# - 같은 데이터 타입으로 구성괸 다차원 배열
# - 각 항목의 타입 : 숫자, 문자, 불
# int8, int16, int32, int64, uint8, uint16, uint32, uint64,
# float32, float64, complex64, complex128 등등

list1 = [1, 2, 3]
print(type(list))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'type'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [8]:
# 각 항목의 데이터 타입이 다른 경우
# -> 큰 데이터 타입으로 변환

list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U11


In [9]:
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


In [10]:
# 각 항목의 데이터 타입을 형 변환

array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [11]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [12]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


In [13]:
# arange(숫자)
# - range 와 비슷하게 0부터 (숫자 - 1)까지

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [14]:
# arange(숫자1, 숫자2)
# - 숫자1부터 (숫자2 - 1)까지

sequence_array2 = np.arange(5, 10)
print(sequence_array2)
print(sequence_array2.dtype, sequence_array2.shape)

[5 6 7 8 9]
int32 (5,)


In [15]:
# zeros
# - 모두 0으로 채운 ndarray 반환
# - dtype 을 입력하지 않으면 기본은 float64

zero_array = np.zeros((3, 2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [16]:
# ones
# - 모두 1로 채운 ndarray 반환
# - dtype 을 입력하지 않으면 기본은 float64

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [17]:
# reshape
# - 차원과 크기 변경
# - 지정한 차원과 크기로 변경하지 못하면 오류 발생

array1 = np.arange(10)
print(array1)
array2 = array1.reshape(2, 5)
print(array2)
array3 = array1.reshape(5, 2)
print(array3)
# array4 = array1.reshape(4, 3) # 오류남

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [18]:
# reshape
# - 자동으로 처리하기 : -1

array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print(array2.shape)
array3 = array1.reshape(5, -1)
print(array3.shape)

[0 1 2 3 4 5 6 7 8 9]
(2, 5)
(5, 2)


In [19]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print(array3d)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [20]:
array5 = array3d.reshape(-1, 1)
print(array5, array5.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)


In [21]:
array6 = array1.reshape(-1, 1)
print(array6, array6.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)


In [22]:
# 단일 값 추출
# - []

array1 = np.arange(1, 10)
print(array1)
value = array1[2]
print(value, type(value))

[1 2 3 4 5 6 7 8 9]
3 <class 'numpy.int32'>


In [23]:
# - 인덱스가 음수이면 뒤에서부터

print(array1[-1], array1[-2])

9 8


In [24]:
# 값 수정

array1[0] = 9
array1[8] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


In [25]:
# 다차원의 경우

array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)
print(array2d[0, 0])
print(array2d[0, 1])
print(array2d[1, 0])
print(array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


In [27]:
# 슬라이싱
# - [시작인덱스 : 종료인덱스] : 시작인덱스부터 (종료인덱스 - 1)까지

array1 = np.arange(1, 10)
print(array1)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [28]:
# - 시작 / 종료 인덱스 생략

array1 = np.arange(1, 10)
print(array1)
array4 = array1[:3]
print(array4)
array5 = array1[3:]
print(array5)
array6 = array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [29]:
# - 다차원의 경우

array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)
print(array2d[0:2, 0:2])
print(array2d[1:3, 0:3])
print(array2d[1:3, :])
print(array2d[:, :])
print(array2d[:2, 1:])
print(array2d[:2, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]


In [30]:
# 팬시 인덱싱 (Fancy Indexing)
# - 리스트나 ndarray 로 인덱스 집합을 지정하면
# 해당 인덱스 값들로 ndarray 를 반환

array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)
array3 = array2d[[0, 1], 2]
print(array3)
array4 = array2d[[0, 1], 0:2]
print(array4)
array5 = array2d[[0, 1]]
print(array5)
array6 = array2d[[0, 2], 1]
print(array6)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]
[2 8]


In [31]:
# 불린 인덱싱
# - 조건문을 만족하는 항목만 추출

array1d = np.arange(1, 10)
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


In [32]:
print(array1d > 5)

[False False False False False  True  True  True  True]


In [33]:
# 행렬 정렬
# - 오름차순

org_array = np.array([3, 1, 9, 5])
print(org_array)
sort_array1 = np.sort(org_array) # 복사하여 정렬하고 결과 반환
print(sort_array1)
print(org_array)
sort_array2 = org_array.sort() # 원본을 정렬
print(sort_array2)
print(org_array)

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]


In [34]:
# - 내림차순

org_array = np.array([3, 1, 9, 5])
print(org_array)
sort_array1 = np.sort(org_array)[::-1]
print(sort_array1)
print(org_array)

[3 1 9 5]
[9 5 3 1]
[3 1 9 5]


In [35]:
# - 다차원의 경우 axis 설정

array2d = np.array([[8, 12],
                    [7, 1]])
print(array2d)
array0 = np.sort(array2d, axis = 0) # axis = 0 : 세로축
print(array0)
array1 = np.sort(array2d, axis = 1) # axis = 1 : 가로축
print(array1)

[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [36]:
# 정렬된 행렬의 인덱스 반환

org_array = np.array([3, 1, 9, 5])
print(org_array)
sort_indices = np.argsort(org_array)
print(sort_indices)

[3 1 9 5]
[1 0 3 2]


In [37]:
# - 내림 차순

org_array = np.array([3, 1, 9, 5])
print(org_array)
sort_indices = np.argsort(org_array)[::-1]
print(sort_indices)

[3 1 9 5]
[2 3 0 1]


In [38]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])
sort_indices = np.argsort(score_array)
print(sort_indices)
print(name_array[sort_indices])

[0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [39]:
# 행렬 내적 (행렬 곱)

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_product = np.dot(A, B)
print(A)
print(B)
print(dot_product)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]


In [40]:
# 전치 행렬

A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print(A)
print(transpose_mat)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
